-- agent_target_db: for Read Agent and Write Agent
CREATE DATABASE agent_target_db;
-- agent_vector_db: for Vector or RAG Agent
CREATE DATABASE agent_vector_db;

-- write_agent: for executing repair tasks
CREATE ROLE write_agent WITH LOGIN PASSWORD 'write_password_123';

-- readonly_agent: for read_probe_server.py
CREATE ROLE readonly_agent WITH LOGIN PASSWORD 'read_password_123';

-- rag_agent: for LangChain's PGVector Store
CREATE ROLE rag_agent WITH LOGIN PASSWORD 'rag_password_123';

-- switch to agent_target_db for write_agent settings
\c agent_target_db

-- grant all privileges to write_agent
GRANT ALL PRIVILEGES ON DATABASE agent_target_db TO write_agent;
GRANT ALL PRIVILEGES ON SCHEMA public TO write_agent;

-- allow write_agent to create, delete, modify tables in public schema
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO write_agent;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO write_agent;

-- ensure future new tables, write_agent also has default permissions
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO write_agent;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO write_agent;

-- in \c agent_target_db for read_agent settings

-- enable slow query statistics extension (probe server needs get_pg_stat_statements tool)
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;

-- basic connection permissions
GRANT CONNECT ON DATABASE agent_target_db TO read_agent;
GRANT USAGE ON SCHEMA public TO read_agent;

-- core defense: only grant SELECT permission to all tables in public schema
GRANT SELECT ON ALL TABLES IN SCHEMA public TO read_agent;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO read_agent;

-- ensure future new tables created by write_agent, readonly_agent can only read!
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO read_agent;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON SEQUENCES TO read_agent;

-- probe privilege: allow readonly_agent to read slow query views
GRANT SELECT ON pg_stat_statements TO read_agent;

-- switch to agent_vector_db
\c agent_vector_db

-- activate pgvector engine
CREATE EXTENSION IF NOT EXISTS vector;

-- grant all privileges to rag_agent;
GRANT ALL PRIVILEGES ON SCHEMA public TO rag_agent;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO rag_agent;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO rag_agent;

-- ensure future tables generated by LangChain, permissions also belong to rag_agent
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO rag_agent;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO rag_agent;