"""create alerts+hypotheses+tickets metadata tables

Revision ID: 07e516d7a865
Revises: d8e3e1a5c098
Create Date: 2026-06-02 06:15:54.415674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07e516d7a865'
down_revision: Union[str, Sequence[str], None] = 'd8e3e1a5c098'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fingerprint', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('instance', sa.Text(), nullable=True),
    sa.Column('cluster_name', sa.Text(), nullable=True),
    sa.Column('database_name', sa.Text(), nullable=True),
    sa.Column('database_role', sa.Text(), nullable=True),
    sa.Column('host', sa.Text(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('environment', sa.Text(), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('annotations', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('generator_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'RECEIVED'"), nullable=False),
    sa.Column('escalation_reason', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('solved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('thread_id', sa.Text(), nullable=True),
    sa.CheckConstraint("database_role IN ('primary', 'replica')", name='ck_alerts_database_role'),
    sa.CheckConstraint("status IN ('RECEIVED', 'RUNNING', 'WAITING_APPROVAL', 'SOLVED', 'RESOLVED', 'ESCALATED', 'FAILED')", name='ck_alerts_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alerts_unique_active_fingerprint', 'alerts', ['fingerprint'], unique=True, postgresql_where=sa.text("(status NOT IN ('SOLVED', 'RESOLVED', 'FAILED', 'ESCALATED'))"))
    op.create_table('hypotheses',
    sa.Column('hypothesis_id', sa.Text(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('validation_actions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('expected_result', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('metric_evidence', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'verified', 'rejected', 'inconclusive')", name='ck_hypotheses_status'),
    sa.CheckConstraint('confidence_score >= 0.0 AND confidence_score <= 1.0', name='ck_hypotheses_confidence_score'),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hypothesis_id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('hypothesis_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('proposed_steps', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('approved_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=False),
    sa.Column('rollback_sql', sa.Text(), nullable=True),
    sa.Column('rollback_note', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_comments', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_duration_ms', sa.Integer(), nullable=True),
    sa.Column('rolled_back_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint("risk_level IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')", name='ck_change_tickets_risk_level'),
    sa.CheckConstraint("status IN ('PENDING', 'APPROVED', 'REJECTED', 'EXECUTING', 'SUCCESS', 'FAILED', 'ROLLED_BACK')", name='ck_change_tickets_status'),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    op.drop_table('hypotheses')
    op.drop_index('idx_alerts_unique_active_fingerprint', table_name='alerts', postgresql_where=sa.text("(status NOT IN ('SOLVED', 'RESOLVED', 'FAILED', 'ESCALATED'))"))
    op.drop_table('alerts')
    # ### end Alembic commands ###
