services:
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: gdb-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./business_rules.yml:/etc/prometheus/business_rules.yml
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  alertmanager:
    image: prom/alertmanager:v0.25.0
    container_name: gdb-alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: gdb-postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://agent:password@host.docker.internal:5432/business_db_b?sslmode=disable"
      # DATA_SOURCE_NAME: "postgresql://agent:password@host.docker.internal:5432/metadata?sslmode=disable"
    ports:
      - "9187:9187"
