global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

rule_files:
  - "business_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    enable_http2: false
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'postgres-cluster'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          cluster_name: ClusterA
          database_role: primary
          environment: DEV
          region: local
          db_host: host.docker.internal
          db_port: "5432"
          db_instance: host.docker.internal:5432

    relabel_configs:
      - source_labels: [__address__]
        target_label: exporter_instance
      - source_labels: [db_instance]
        target_label: instance
